### ISSUE TITLE
No way to logout

### ISSUE THREAD

**Issue by pcperini** [pcperini/Tusk---Issues#14]
## Expected Behavior
- Go to the account tab
- Go to settings
- Tap logout button

## Actual Behavior
- Settings button is disabled

### See also:

https://mastodon.social/web/statuses/100662433506175780

**Comment by pcperini** [comment]
Fixed in b29

**Comment by gerdemann** [comment]
I still can't log out.
My account page Looks like https://www.dropbox.com/s/33a5kd4fxvbvzc1/IMG_0599.PNG?dl=0
My security token is revoked.
